version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: feature_flag_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: feature_flags
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  test-postgres:
    image: postgres:15
    container_name: feature_flag_test_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_feature_flags
    ports:
      - "5433:5432"  # Run test database on a different port
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: feature_flag_redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: feature_flag_app
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      PORT: 8080
      DATABASE_URL: postgres://postgres:password@postgres:5432/feature_flags?sslmode=disable
      REDIS_URL: redis:6379
      JWT_SECRET: mysecretkey
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  postgres_test_data:
  redis_data:
